stages:
- name: Build
  steps:
  - runScriptConfig:
      image: suite-cloud/suite-cloud-maven
      shellScript: mvn deploy:deploy-file
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: suite-cloud/suite-cloud-parent
      pushRemote: true
      registry: 127.0.0.1:34709
notification: {}
