stages:
- name: Build
  steps:
  - runScriptConfig:
      image: 10.0.0.203:5000/suite-cloud-maven
      shellScript: mvn deploy:deploy-file
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: suite-cloud-parent
      pushRemote: true
      registry: 10.0.0.203:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
